# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oadb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='adaptor',
            name='barcode',
            field=models.CharField(default='', max_length=100),
        ),
    ]
