# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oadb', '0002_auto_20170815_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kit',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='kit',
            name='vendor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kit',
            name='version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
