# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oadb', '0003_auto_20170815_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adaptor',
            old_name='expression',
            new_name='sequence',
        ),
    ]
