# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oadb', '0005_adaptor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
