# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oadb', '0006_database_name_uniq_20170815_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adaptor',
            old_name='sequence',
            new_name='full_sequence',
        ),
        migrations.AddField(
            model_name='adaptor',
            name='index_sequence',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adaptor',
            name='index_type',
            field=models.CharField(choices=[(':5', '5'), (':7', '7')], default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adaptor',
            name='universal_sequence',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
