# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oadb', '0007_auto_20170815_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='five_prime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='five', to='oadb.Adaptor'),
        ),
        migrations.AddField(
            model_name='run',
            name='three_prime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='three', to='oadb.Adaptor'),
        ),
        migrations.AlterField(
            model_name='adaptor',
            name='index_type',
            field=models.CharField(choices=[('five', 'five'), ('seven', 'seven')], max_length=5),
        ),
        migrations.AlterField(
            model_name='run',
            name='accession',
            field=models.CharField(max_length=100),
        ),
    ]
