# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 16:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oadb', '0008_auto_20170816_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='is_inferred',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='run',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adaptor',
            name='index_type',
            field=models.CharField(choices=[('i5', 'i5'), ('i7', 'i7')], max_length=5),
        ),
        migrations.AlterField(
            model_name='run',
            name='database',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oadb.Database'),
        ),
        migrations.AlterField(
            model_name='run',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='run',
            name='sequencing_instrument',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
