# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oadb', '0009_auto_20170816_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='kit',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kit',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kit',
            name='subkit',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kit',
            name='vendor',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kit',
            name='version',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='kit',
            name='model',
        ),
        migrations.RemoveField(
            model_name='kit',
            name='name',
        ),
        migrations.AlterUniqueTogether(
            name='kit',
            unique_together=set([('kit', 'subkit', 'version')]),
        ),
    ]
