# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oadb', '0011_auto_20170816_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaptor',
            name='kit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptors', to='oadb.Kit'),
        ),
    ]
