# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oadb', '0012_auto_20170816_1936'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adaptor',
            new_name='Adapter',
        ),
        migrations.AlterModelOptions(
            name='adapter',
            options={'ordering': ('kit', 'barcode')},
        ),
        migrations.AlterModelOptions(
            name='database',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='kit',
            options={'ordering': ('vendor', 'kit', 'subkit')},
        ),
        migrations.AlterModelOptions(
            name='run',
            options={'ordering': ('accession', 'user')},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('un',)},
        ),
        migrations.AlterField(
            model_name='user',
            name='un',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterModelTable(
            name='adapter',
            table='oadb_adaptor',
        ),
    ]
