# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oadb', '0014_adapterkit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adapter',
            name='kit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adapters', to='oadb.Kit'),
        ),
    ]
