# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oadb', '0015_auto_20170819_0352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',)},
        ),
        migrations.AlterField(
            model_name='user',
            name='un',
            field=models.CharField(max_length=150),
        ),
    ]
